name: Create PR in android-news-app when bridget is updated

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and copy bridget.jar
    runs-on: 4core-ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ secrets.GU_ANDROID_CLIENT_ID }}
        private-key: ${{ secrets.GU_ANDROID_PRIVATE_KEY }}
        permission-contents: write
        permission-pull-requests: write

    - uses: actions/checkout@v5
      with:
        # Needed so that app's token is used to authorise git ops in 'Add jar to android-news-app repo' step
        token: ${{ steps.app-token.outputs.token }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

    - name: Build jar
      run: |
        ./gradlew :library:build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: library-jar
        path: |
          library/build/libs/library.jar

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Add jar to android-news-app repo
      run: |
        ./scripts/create_bridget_pr.sh
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_USER_NAME: "${{ steps.app-token.outputs.app-slug }}[bot]"
        GITHUB_USER_EMAIL: "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
