name: Create PR in android-news-app when bridget is updated

on:
  push:
    branches:
      - 'main'
    paths:
      - 'library/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and copy bridget.jar
    runs-on: 4core-ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build jar
      run: |
        ./gradlew :library:build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: library-jar
        path: |
          library/build/libs/library.jar

    - name: Add jar to android-news-app repo
      env:
        GUARDIANANDROID_PAT: ${{ secrets.GUARDIANANDROID_PAT }}
      run: |
        ./scripts/create_bridget_pr.sh